[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "Unicode-3.0",
    "ISC",
    "OpenSSL"
]
exceptions = [
    { allow = ["MPL-2.0"], crate = "webpki-root-certs" },
]

[[licenses.clarify]]
crate = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 }
]

[licenses.private]
ignore = true

# https://embarkstudios.github.io/cargo-deny/checks/bans/cfg.html
[bans]
# Lint level for when multiple versions of the same crate are detected
multiple-versions = "deny"
# Lint level for when a crate version requirement is `*`
wildcards = "deny"

skip = [
    { crate = "bitflags@1.3.2", reason = "Caused by: png. Fixed in image-rs/image-png#553" },
    { crate = "itertools@0.12.1", reason = "Caused by: rav1e. Fixed in xiph/rav1e#3379" },
    
]
skip-tree = [
    { crate = "windows-sys", reason = "Never up to date" },
    { crate = "matchers@0.1.0", reason = "Caused by: tracing-subscriber" },
    { crate = "thiserror@1.0.69", reason = "Caused by: geojson, jni, rav1e. Fixed in georust/geojson#247, jni-rs/jni-rs#559, xiph/rav1e#3407" },
]

# This section is considered when running `cargo deny check sources`.
# More documentation about the 'sources' section can be found here:
# https://embarkstudios.github.io/cargo-deny/checks/sources/cfg.html
[sources]
# Lint level for what to happen when a crate from a crate registry that is not
# in the allow list is encountered
unknown-registry = "deny"
# Lint level for what to happen when a crate from a git repository that is not
# in the allow list is encountered
unknown-git = "deny"
# List of URLs for allowed crate registries. Defaults to the crates.io index
# if not specified. If it is specified but empty, no registries are allowed.
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
# List of URLs for allowed Git repositories
allow-git = []

[sources.allow-org]
# github.com organizations to allow git sources for
github = []
# gitlab.com organizations to allow git sources for
gitlab = []
# bitbucket.org organizations to allow git sources for
bitbucket = []
