name: Rust

on:
  push:
    branches: [ "main" ]
  merge_group:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: '-D warnings --cfg tracing_unstable'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container: rust:1.84-bookworm

    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          echo "deb http://deb.debian.org/debian bookworm-backports main" | tee /etc/apt/sources.list.d/bookworm-backports.list
          apt-get update
          apt-get install -y pkg-config libclang-dev libheif1/bookworm-backports libheif-dev/bookworm-backports

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Run tests
        run: cargo test

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - name: Run rustfmt
        run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    container: rust:1.84-bookworm
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          echo "deb http://deb.debian.org/debian bookworm-backports main" | tee /etc/apt/sources.list.d/bookworm-backports.list
          apt-get update
          apt-get install -y pkg-config libclang-dev libheif1/bookworm-backports libheif-dev/bookworm-backports

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
      - name: Install Clippy
        run: rustup component add clippy

      - name: Run clippy
        run: cargo clippy --all-targets --all

  deny:
    name: Cargo Deny
    runs-on: ubuntu-latest
    strategy:
      matrix:
        checks:
          - advisories
          - bans licenses sources
    continue-on-error: ${{ matrix.checks == 'advisories' }}
    steps:
      - uses: actions/checkout@v4
      - uses: EmbarkStudios/cargo-deny-action@v2
        with:
          command: check ${{ matrix.checks }}
